preset:
  - name: 测试预设1
    describe: 测试预设1的描述
    config:
      - name: 测试配置1
        describe: 测试配置1的描述 
        rule: keyword
        keyword: [高兴,伤心]
        action: 
          - name: move
            describe: 移动
            targetDir: /Users/kerin/Downloads/music

          - name: copy
            describe: 复制
            targetDir: /Users/kerin/Downloads/music

          - name: remove
            describe: 删除
